"""Add email to users table

Revision ID: 17748ec4be9c
Revises: 78dae326e2ea
Create Date: 2024-10-02 03:48:01.146307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17748ec4be9c'
down_revision = '78dae326e2ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wallets_id', table_name='wallets')
    op.drop_table('wallets')
    op.drop_index('ix_subscriptions_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_gas_alerts_id', table_name='gas_alerts')
    op.drop_table('gas_alerts')
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_column('users', 'email')
    op.create_table('gas_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='gas_alerts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gas_alerts_pkey')
    )
    op.create_index('ix_gas_alerts_id', 'gas_alerts', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subscriptions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey')
    )
    op.create_index('ix_subscriptions_id', 'subscriptions', ['id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blockchain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wallets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wallets_pkey'),
    sa.UniqueConstraint('address', name='wallets_address_key')
    )
    op.create_index('ix_wallets_id', 'wallets', ['id'], unique=False)
    # ### end Alembic commands ###
