"""Create wallets table

Revision ID: 78dae326e2ea
Revises: e8e6d9689534
Create Date: 2024-09-30 03:46:42.050635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78dae326e2ea'
down_revision = 'e8e6d9689534'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
