"""Create subscriptions table

Revision ID: e8e6d9689534
Revises: 7c534168e46c
Create Date: 2024-09-30 03:37:37.322282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e6d9689534'
down_revision = '7c534168e46c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
